function [output] = pasteImage(background, foreground, alpha_data)
% pasteImage pastes the foreground image onto the background image
[b_h, b_w, ~] = size(background);
[f_h, f_w, ~] = size(foreground);
size(alpha_data);
alpha_data = double(alpha_data)/255;

if (mod(f_h,2) ~= 0 && mod(f_w,2) == 0)
    h = (floor(b_h/2)+floor(f_h/2)) - (floor(b_h/2)-floor(f_h/2));
    w = (floor(b_w/2)+floor(f_w/2)) - (floor(b_w/2)-floor(f_w/2)+1);
    background(floor(b_h/2)-floor(f_h/2):floor(b_h/2)+floor(f_h/2),...
               floor(b_w/2)-floor(f_w/2)+1:floor(b_w/2)+floor(f_w/2),:) = ...
                floor((1-alpha_data).*double(background(floor(b_h/2)-floor(f_h/2):floor(b_h/2)+floor(f_h/2),...
                                                        floor(b_w/2)-floor(f_w/2)+1:floor(b_w/2)+floor(f_w/2),:)) ...
                + alpha_data.*double(foreground));
elseif (mod(f_h,2) == 0 && mod(f_w,2) ~= 0)
    h = (floor(b_h/2)+floor(f_h/2)) - (floor(b_h/2)-floor(f_h/2)+1);
    w = (floor(b_w/2)+floor(f_w/2)) - (floor(b_w/2)-floor(f_w/2));
    background(floor(b_h/2)-floor(f_h/2)+1:floor(b_h/2)+floor(f_h/2),...
               floor(b_w/2)-floor(f_w/2):floor(b_w/2)+floor(f_w/2),:) = ...
                floor((1-alpha_data).*double(background(floor(b_h/2)-floor(f_h/2)+1:floor(b_h/2)+floor(f_h/2),...
                                                        floor(b_w/2)-floor(f_w/2):floor(b_w/2)+floor(f_w/2),:)) ...
                + alpha_data.*double(foreground));
elseif (mod(f_h,2) ~= 0 && mod(f_w,2) ~= 0)
    h = (floor(b_h/2)+floor(f_h/2)) - (floor(b_h/2)-floor(f_h/2));
    w = (floor(b_w/2)+floor(f_w/2)) - (floor(b_w/2)-floor(f_w/2));
    background(floor(b_h/2)-floor(f_h/2):floor(b_h/2)+floor(f_h/2),...
               floor(b_w/2)-floor(f_w/2):floor(b_w/2)+floor(f_w/2),:) = ...
                floor((1-alpha_data).*double(background(floor(b_h/2)-floor(f_h/2):floor(b_h/2)+floor(f_h/2),...
                                                        floor(b_w/2)-floor(f_w/2):floor(b_w/2)+floor(f_w/2),:)) ...
                + alpha_data.*double(foreground));
else
    h = (floor(b_h/2)+floor(f_h/2)) - (floor(b_h/2)-floor(f_h/2)+1);
    w = (floor(b_w/2)+floor(f_w/2)) - (floor(b_w/2)-floor(f_w/2)+1);
    background(floor(b_h/2)-floor(f_h/2)+1:floor(b_h/2)+floor(f_h/2),...
               floor(b_w/2)-floor(f_w/2)+1:floor(b_w/2)+floor(f_w/2),:) = ...
                floor((1-alpha_data).*double(background(floor(b_h/2)-floor(f_h/2)+1:floor(b_h/2)+floor(f_h/2),...
                                                        floor(b_w/2)-floor(f_w/2)+1:floor(b_w/2)+floor(f_w/2),:)) ...
                + alpha_data.*double(foreground));
end
output = background;
end